"""Synthetic-b411 dataset — SAXS-TT scan forward-projected from a known SH volume.

Generated by ``notebooks/NpyToDataContainer.ipynb``: an ``(X, Y, Z, 45)`` SH
ground-truth tensor is loaded directly from an ``.npy`` file and forward-projected
over Fibonacci-hemisphere directions (using b411 detector geometry) to produce the
projections/geometry saved here.  Like ``fiber-synthetic``, the ground truth is
known exactly by construction — no mumott/NAF reconstruction is needed — and is
cached alongside the HDF5 file as an ``.npy`` + JSON sidecar via
``smartt.saxs_naf.cache.save_recon``.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from .base import SmarttDataContainer


class SyntheticB411DataContainer(SmarttDataContainer):
    """Single-mount synthetic dataset with a known SH ground truth.

    No remount or combined DC — one HDF5 file, load and go.  The geometry was
    generated with b411 detector metadata, whose saved ``full_circle_covered``
    flag is ``True`` even though the Fibonacci-hemisphere directions cover only a
    missing-wedge-limited hemisphere, so it must be overridden on load.
    """

    name = "synthetic-b411"
    has_remount = False
    has_combined = False

    _PATH_DATA = Path("/myhome/data/smartt/shared/synthetic_b411/dataset_from_npy.h5")
    _CACHE_DIR = Path("/myhome/data/smartt/shared/synthetic_b411/recon_cache")

    def get_cache_dir(self) -> Path:
        self._CACHE_DIR.mkdir(parents=True, exist_ok=True)
        return self._CACHE_DIR

    def get_main_dc(self):
        from mumott.data_handling import DataContainer
        dc = DataContainer(str(self._PATH_DATA))
        dc.geometry.full_circle_covered = False
        return dc

    def get_ground_truth(self) -> np.ndarray:
        """Load the exact ``(X, Y, Z, 45)`` SH tensor used to generate this dataset.

        Reads the ``ground_truth_*.npy`` sidecar written by
        ``notebooks/NpyToDataContainer.ipynb`` via ``save_recon`` — no
        reconstruction needed, this dataset's ground truth is exact by
        construction. If multiple sidecars exist (e.g. from re-runs with
        different generation params), the most recently modified one is used.
        """
        matches = sorted(self._CACHE_DIR.glob("ground_truth_*.npy"), key=lambda p: p.stat().st_mtime)
        if not matches:
            raise FileNotFoundError(
                f"No ground-truth sidecar found in {self._CACHE_DIR}. "
                "Run notebooks/NpyToDataContainer.ipynb to generate it."
            )
        return np.load(matches[-1])
